worker_processes auto;

events { worker_connections 1024; }

http {
  upstream legacy_php {
    server legacy-php:9000;
  }

  upstream catalog_go {
    server catalog-service:8080;
  }

  upstream inventory_go {
    server inventory-service:8080;
  }

  upstream ordering_go {
    server ordering-service:8080;
  }

  map $http_x_flag_catalog_v2 $catalog_target {
    default legacy_php;
    "10" legacy_php;
    "50" catalog_go;
    "100" catalog_go;
  }

  map $http_x_flag_inventory_v2 $inventory_target {
    default legacy_php;
    "10" legacy_php;
    "50" inventory_go;
    "100" inventory_go;
  }

  map $http_x_flag_ordering_v2 $ordering_target {
    default legacy_php;
    "10" legacy_php;
    "50" ordering_go;
    "100" ordering_go;
  }

  server {
    listen 80;

    location /api/catalog/ {
      proxy_pass http://$catalog_target;
    }

    location /api/inventory/ {
      proxy_pass http://$inventory_target;
    }

    location /api/orders/ {
      proxy_pass http://$ordering_target;
    }

    location / {
      proxy_pass http://legacy_php;
    }
  }
}
